// <auto-generated />
using System;
using LotTakip.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LotTakip.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007135056_IlkSema")]
    partial class IlkSema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LotTakip.Entity.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanici", (string)null);
                });

            modelBuilder.Entity("LotTakip.Entity.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Iletisim")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Musteri", (string)null);
                });

            modelBuilder.Entity("LotTakip.Entity.Parca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MinStok")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Parca", null, t =>
                        {
                            t.HasCheckConstraint("CK_Parca_MinStok", "[MinStok] >= 0");
                        });
                });

            modelBuilder.Entity("LotTakip.Entity.Satis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Satis", (string)null);
                });

            modelBuilder.Entity("LotTakip.Entity.SatisKalemi", b =>
                {
                    b.Property<int>("SatisId")
                        .HasColumnType("int");

                    b.Property<int>("UretimId")
                        .HasColumnType("int");

                    b.HasKey("SatisId", "UretimId");

                    b.HasIndex("UretimId")
                        .IsUnique();

                    b.ToTable("SatisKalemi", (string)null);
                });

            modelBuilder.Entity("LotTakip.Entity.StokDuzeltme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StokLotuId")
                        .HasColumnType("int");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanKullaniciId");

                    b.HasIndex("StokLotuId");

                    b.ToTable("StokDuzeltme", null, t =>
                        {
                            t.HasCheckConstraint("CK_StokDuzeltme_Aciklama", "LEN([Aciklama]) > 0");

                            t.HasCheckConstraint("CK_StokDuzeltme_Miktar", "[Miktar] <> 0");
                        });
                });

            modelBuilder.Entity("LotTakip.Entity.StokLotu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("GeriCagrildi")
                        .HasColumnType("bit");

                    b.Property<int>("GirisAdet")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("GirisZamani")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("KalanAdet")
                        .HasColumnType("int");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ParcaId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SiparisNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("SiparisTarihi")
                        .HasColumnType("date");

                    b.Property<int>("TedarikciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotNo")
                        .IsUnique();

                    b.HasIndex("OlusturanKullaniciId");

                    b.HasIndex("TedarikciId");

                    b.HasIndex("ParcaId", "GeriCagrildi", "SiparisTarihi", "Id");

                    b.ToTable("StokLotu", null, t =>
                        {
                            t.HasCheckConstraint("CK_StokLotu_GirisAdet", "[GirisAdet] > 0");

                            t.HasCheckConstraint("CK_StokLotu_KalanAdet", "[KalanAdet] >= 0");
                        });
                });

            modelBuilder.Entity("LotTakip.Entity.Tedarikci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Iletisim")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Tedarikci", (string)null);
                });

            modelBuilder.Entity("LotTakip.Entity.Uretim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("Tarih")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanKullaniciId");

                    b.HasIndex("SeriNo")
                        .IsUnique();

                    b.HasIndex("UrunId");

                    b.ToTable("Uretim", (string)null);
                });

            modelBuilder.Entity("LotTakip.Entity.UretimTuketim", b =>
                {
                    b.Property<int>("UretimId")
                        .HasColumnType("int");

                    b.Property<int>("StokLotuId")
                        .HasColumnType("int");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.HasKey("UretimId", "StokLotuId");

                    b.HasIndex("StokLotuId");

                    b.ToTable("UretimTuketim", null, t =>
                        {
                            t.HasCheckConstraint("CK_UretimTuketim_Adet", "[Adet] > 0");
                        });
                });

            modelBuilder.Entity("LotTakip.Entity.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeriOneki")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.HasIndex("SeriOneki")
                        .IsUnique();

                    b.ToTable("Urun", (string)null);
                });

            modelBuilder.Entity("LotTakip.Entity.UrunAgaci", b =>
                {
                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.Property<int>("ParcaId")
                        .HasColumnType("int");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.HasKey("UrunId", "ParcaId");

                    b.HasIndex("ParcaId");

                    b.ToTable("UrunAgaci", null, t =>
                        {
                            t.HasCheckConstraint("CK_UrunAgaci_Adet", "[Adet] > 0");
                        });
                });

            modelBuilder.Entity("LotTakip.Entity.Satis", b =>
                {
                    b.HasOne("LotTakip.Entity.Musteri", "Musteri")
                        .WithMany("Satislar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LotTakip.Entity.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("LotTakip.Entity.SatisKalemi", b =>
                {
                    b.HasOne("LotTakip.Entity.Satis", "Satis")
                        .WithMany("Kalemler")
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LotTakip.Entity.Uretim", "Uretim")
                        .WithOne("SatisKalemi")
                        .HasForeignKey("LotTakip.Entity.SatisKalemi", "UretimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Satis");

                    b.Navigation("Uretim");
                });

            modelBuilder.Entity("LotTakip.Entity.StokDuzeltme", b =>
                {
                    b.HasOne("LotTakip.Entity.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LotTakip.Entity.StokLotu", "StokLotu")
                        .WithMany("Duzeltmeler")
                        .HasForeignKey("StokLotuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");

                    b.Navigation("StokLotu");
                });

            modelBuilder.Entity("LotTakip.Entity.StokLotu", b =>
                {
                    b.HasOne("LotTakip.Entity.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LotTakip.Entity.Parca", "Parca")
                        .WithMany("Lotlar")
                        .HasForeignKey("ParcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LotTakip.Entity.Tedarikci", "Tedarikci")
                        .WithMany("Lotlar")
                        .HasForeignKey("TedarikciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");

                    b.Navigation("Parca");

                    b.Navigation("Tedarikci");
                });

            modelBuilder.Entity("LotTakip.Entity.Uretim", b =>
                {
                    b.HasOne("LotTakip.Entity.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LotTakip.Entity.Urun", "Urun")
                        .WithMany("Uretimler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("LotTakip.Entity.UretimTuketim", b =>
                {
                    b.HasOne("LotTakip.Entity.StokLotu", "StokLotu")
                        .WithMany("Tuketimler")
                        .HasForeignKey("StokLotuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LotTakip.Entity.Uretim", "Uretim")
                        .WithMany("Tuketimler")
                        .HasForeignKey("UretimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StokLotu");

                    b.Navigation("Uretim");
                });

            modelBuilder.Entity("LotTakip.Entity.UrunAgaci", b =>
                {
                    b.HasOne("LotTakip.Entity.Parca", "Parca")
                        .WithMany("AgacSatirlari")
                        .HasForeignKey("ParcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LotTakip.Entity.Urun", "Urun")
                        .WithMany("Agac")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parca");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("LotTakip.Entity.Musteri", b =>
                {
                    b.Navigation("Satislar");
                });

            modelBuilder.Entity("LotTakip.Entity.Parca", b =>
                {
                    b.Navigation("AgacSatirlari");

                    b.Navigation("Lotlar");
                });

            modelBuilder.Entity("LotTakip.Entity.Satis", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("LotTakip.Entity.StokLotu", b =>
                {
                    b.Navigation("Duzeltmeler");

                    b.Navigation("Tuketimler");
                });

            modelBuilder.Entity("LotTakip.Entity.Tedarikci", b =>
                {
                    b.Navigation("Lotlar");
                });

            modelBuilder.Entity("LotTakip.Entity.Uretim", b =>
                {
                    b.Navigation("SatisKalemi");

                    b.Navigation("Tuketimler");
                });

            modelBuilder.Entity("LotTakip.Entity.Urun", b =>
                {
                    b.Navigation("Agac");

                    b.Navigation("Uretimler");
                });
#pragma warning restore 612, 618
        }
    }
}
