<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- Swagger açıklamaları için; belgesiz üyeler için uyarı verme -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LotTakip.Business\LotTakip.Business.csproj" />
    <ProjectReference Include="..\LotTakip.Shared\LotTakip.Shared.csproj" />
    <ProjectReference Include="..\LotTakip.DataAccess\LotTakip.DataAccess.csproj" />
  </ItemGroup>

</Project>
